version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplePassword
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsletter
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://newsletter:examplePassword@mongodb:27017/newsletter
      NODE_ENV: development

volumes:
  mongodb_data:


networks:
  default:
    external:
      name: nginx-proxy