version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplePassword
    volumes:
      - mongodb_data:/data/db

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsletter
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:examplePassword@mongodb:27017/newsletter
      NODE_ENV: development
volumes:
  mongodb_data:
